Fix release notes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,6 +15,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+          tags: true
       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
@@ -34,18 +35,20 @@ jobs:
         id: notes
         run: |
           LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
+          echo "Last tag: $LAST_TAG"
           if [ -n "$LAST_TAG" ]; then
               RELEASE_NOTES=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s")
           else
               RELEASE_NOTES=$(git log --pretty=format:"- %s")
           fi
           if [ -z "$RELEASE_NOTES" ]; then
-              RELEASE_NOTES="Initial release"
+              echo "No commits found since the last tag. Aborting release."
+              exit 1
           fi
           echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
           echo "$RELEASE_NOTES" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
-          echo $RELEASE_NOTES
+          echo "$RELEASE_NOTES"
 
       - name: Decode Keystore
         run: |
